/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TodoApp;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainTest {
    @Test void appHasAGreeting() {
       Mainp classUnderTest = newMainp();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    private Mainp newMainp() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
